name: Release Chrome Extension

on: [workflow_dispatch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build and Test
        run: pnpm build-test
        env:
          CI: true
          VITEST_SEGFAULT_RETRY: 3

      - name: Upload & release Extension
        uses: mnao305/chrome-extension-upload@3.0.0
        with:
          file-path: packages/extension/dist.zip
          extension-id: kmcfjchnmmaeeagadbhoofajiopoceel
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
